api:
  host: 'localhost'
  port: 50446
  schema: 'http'
containers:
  - host: 'localhost'
    port: 50443
    schema: 'http'
    emb_name: 'name_1'
  - host: 'localhost'
    port: 50445
    schema: 'http'
    emb_name: 'name_2'
queue:
  maxsize: 100
  retry_attempts: 3
log:
  level: 'INFO'
  output_file:

