api:
  host: '0.0.0.0'
  port: 50443
  schema: 'http'
containers:
  - host: 'antiplagiat_prod_3-antiplagiat-1'
    port: 50446
    schema: 'http'
    emb_name: 'name_1'
  - host: 'antiplagiat'
    port: 50445
    schema: 'http'
    emb_name: 'name_2'
queue:
  maxsize: 100
  retry_attempts: 3
log:
  level: 'INFO'
  output_file:

